version: '3' 
services:
    jenkins:
      container_name: jenkins
      image: docker.io/mguazzardo/myjenkins:0.2
      ports:
        - "8080:8080"
      networks:
        - net
    sonarqube:
      container_name: sonarqube
      image: docker.io/mguazzardo/mysonarqube:0.1
      ports:
        - "9000:9000"
      environment:
        SONARQUBE_USERNAME: admin
        SONARQUBE_PASSWORD: mipassword
      networks:
      - net
networks:
  net:
